### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by raycohen** [raycohen/ember-validation#1]
- [ ] documentation
- [ ] better test suite
- [ ] suite of basic common validations
- [ ] custom validation functions
- [ ] validations with multiple dependent keys
- [ ] ability to know if a property failed a specific validation (supply a special key, add boolean prop to errors object in addition to the message in errors.validatedProp)
- [ ] figure out if another name would help explain how this validation library is different. `ember-validations-unmixed`
